### ISSUE TITLE
Welcome Melanie!

### ISSUE THREAD

**Issue by daiyi** [czf-con/orga#16]
Melanie is going to help us make this happen \o/ Yay!

**ASAP to kick off other steps**
- [x] add to contact sheet: @mkremins 

**orgaisational**
- [x] add to orga group chat
- [x] add to github org
- [x] add to shared goog drive

**etc**
- [x] add to [@czf_con](https://twitter.com/czf_con) tweetdeck

**Comment by daiyi** [comment]
I'd also like to take this moment to advertise this ongoing onboarding checklist :D https://github.com/czf-con/orga/wiki/Onboarding-checklist

**Comment by meldckn** [comment]
(Thanks so much for this btw! Honored to be working with you on ziney things again, @daiyi! (Remember middle school? Omg))

Also, @mkremins just added me to the Tweetdeck AND showed me how to use Tweetdeck! So this list is finally complete!!
